name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Create release artifacts
        run: |
          mkdir -p release
          cp target/release/fhe_mini_project release/
          cp target/release/examples/interactive_demo release/
          cp README.md release/
          cp -r data release/
          tar czf fhe_mini_project-linux-x86_64.tar.gz -C release .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./fhe_mini_project-linux-x86_64.tar.gz
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
